Starting C++ node A...
Starting C++ node B...
Starting C++ node C...
Starting C++ node D...
Starting C++ node E...
Starting C++ node G...
Starting Python node F with python3.10...
Starting Python node H with python3.10...
Starting Python node I with python3.10...

All nodes started. Logs available in logs/
Monitor a node: tail -f logs/A.log
Stop all nodes: bash scripts/stop_all.sh
