# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import parking_violation_query_pb2 as parking__violation__query__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in parking_violation_query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParkingViolationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitQuery = channel.unary_unary(
                '/parkingviolation.ParkingViolationService/SubmitQuery',
                request_serializer=parking__violation__query__pb2.QueryRequest.SerializeToString,
                response_deserializer=parking__violation__query__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ForwardQuery = channel.unary_unary(
                '/parkingviolation.ParkingViolationService/ForwardQuery',
                request_serializer=parking__violation__query__pb2.ForwardRequest.SerializeToString,
                response_deserializer=parking__violation__query__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/parkingviolation.ParkingViolationService/CancelQuery',
                request_serializer=parking__violation__query__pb2.CancelRequest.SerializeToString,
                response_deserializer=parking__violation__query__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/parkingviolation.ParkingViolationService/HealthCheck',
                request_serializer=parking__violation__query__pb2.HealthRequest.SerializeToString,
                response_deserializer=parking__violation__query__pb2.HealthResponse.FromString,
                _registered_method=True)


class ParkingViolationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParkingViolationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuery,
                    request_deserializer=parking__violation__query__pb2.QueryRequest.FromString,
                    response_serializer=parking__violation__query__pb2.QueryResponse.SerializeToString,
            ),
            'ForwardQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardQuery,
                    request_deserializer=parking__violation__query__pb2.ForwardRequest.FromString,
                    response_serializer=parking__violation__query__pb2.ForwardResponse.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=parking__violation__query__pb2.CancelRequest.FromString,
                    response_serializer=parking__violation__query__pb2.CancelResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=parking__violation__query__pb2.HealthRequest.FromString,
                    response_serializer=parking__violation__query__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parkingviolation.ParkingViolationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parkingviolation.ParkingViolationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParkingViolationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parkingviolation.ParkingViolationService/SubmitQuery',
            parking__violation__query__pb2.QueryRequest.SerializeToString,
            parking__violation__query__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parkingviolation.ParkingViolationService/ForwardQuery',
            parking__violation__query__pb2.ForwardRequest.SerializeToString,
            parking__violation__query__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parkingviolation.ParkingViolationService/CancelQuery',
            parking__violation__query__pb2.CancelRequest.SerializeToString,
            parking__violation__query__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parkingviolation.ParkingViolationService/HealthCheck',
            parking__violation__query__pb2.HealthRequest.SerializeToString,
            parking__violation__query__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
